### ISSUE TITLE
Does not work for 1.8+

### ISSUE THREAD

**Issue by DaitiDay** [mally8/zen-browser-no-sidebar-scrollbar#7]
As for the title, this mod does not fork for 1.8+. I don't know what changed, I tried to write a css snippet myself but with no success.

**Comment by mally8** [comment]
I will make a pr later but for now if you want this is the snippet.
```css
#zen-tabs-wrapper {
    scrollbar-width: none !important;
} 
```
seems to be just the element id change ^^
