### ISSUE TITLE
Does not work on 1.12.7b

### ISSUE THREAD

**Issue by 8bytes-1Bit** [mally8/zen-browser-no-sidebar-scrollbar#9]
![Image](https://github.com/user-attachments/assets/da19f62b-c6a6-410d-9602-4ce342b41cff)

)

![Image](https://github.com/user-attachments/assets/8c701c12-1920-401e-9a64-99d6cdbf2dae)

**Comment by mally8** [comment]
Waiting for the PR to get merged in the theme store.
Meanwhile if don't wanna wait and have Live Editing configured you can add these lines;
```css
    scrollbox:nth-child(5) {
        scrollbar-width: none !important;
    }
```
if you did and it did not work let me know, Thanks!
